// Enhanced Game Data Configuration File - Objective Facts Only
// All subjective categories removed - only verifiable facts remain

window.GAME_DATA = {
  playerMatches: {
    cricket: {
      // Indian Players
      "Virat Kohli": [
        "Indian Player",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Current RCB Player",
        "RCB Player Never Won IPL",
        "Scored 13000+ ODI Runs",
        "Cover Drive Specialist",
        "Most International Centuries While Chasing",
        "Married to Actress",
        "Has Children",
      ],
      "MS Dhoni": [
        "Indian Player",
        "Wicket-Keeper Batsman",
        "Former CSK Captain",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "2011 World Cup Winning Captain",
        "2007 T20 WC Winner",
        "Helicopter Shot Creator",
        "Most Stumpings in Career",
        "Lieutenant Colonel in Army",
        "Married",
        "Has Children",
      ],
      "Rohit Sharma": [
        "Indian Player",
        "Right-Handed Batsman",
        "Current MI Player",
        "Current Test Captain",
        "Current ODI Captain",
        "Current T20I Captain",
        "Only Player with 3 ODI Double Centuries",
        "Highest Individual ODI Score (264)",
        "Pull Shot Specialist",
        "Hitman Nickname",
        "Married",
        "Has Children",
      ],
      "Sachin Tendulkar": [
        "Indian Player",
        "Right-Handed Batsman",
        "Former MI Player",
        "Retired Legend",
        "First to 100 International Centuries",
        "Most Runs in International Cricket",
        "First ODI Double Century Scorer",
        "Played 6 World Cups",
        "200 Test Matches Played",
        "Married",
        "Has Children",
      ],
      "Jasprit Bumrah": [
        "Indian Player",
        "Fast Bowler",
        "Current MI Player",
        "Yorker Specialist",
        "Fastest Indian to 100 ODI Wickets",
        "Current Test Vice-Captain",
        "Married to Presenter",
      ],
      "R Ashwin": [
        "Indian Player",
        "Off-Spinner",
        "All-Rounder",
        "Current RR Player",
        "Engineer Turned Cricketer",
        "Carrom Ball Specialist",
        "Most Wickets in WTC",
        "Mankading Incident",
        "YouTube Cricket Analyst",
        "Most 5-Wicket Hauls for India",
        "Married",
        "Has Children",
      ],
      "Ravindra Jadeja": [
        "Indian Player",
        "Left-Arm Spinner",
        "All-Rounder",
        "Current CSK Player",
        "Sword Celebration",
        "Triple Century Scorer",
        "Sir Jadeja Nickname",
        "Married",
        "Has Children",
      ],
      "KL Rahul": [
        "Indian Player",
        "Right-Handed Batsman",
        "Wicket-Keeper Batsman",
        "Current LSG Captain",
        "Former PBKS Captain",
        "Fastest Indian T20I Century",
        "Orange Cap Winner",
      ],
      "Hardik Pandya": [
        "Indian Player",
        "All-Rounder",
        "Fast-Bowling All-Rounder",
        "Current MI Captain",
        "Former GT Captain",
        "GT Captain First Season Win",
        "Comeback from Surgery",
        "Married",
        "Has Children",
      ],
      "Rishabh Pant": [
        "Indian Player",
        "Wicket-Keeper Batsman",
        "Left-Handed Batsman",
        "Current DC Captain",
        "Car Accident Survivor",
        "Reverse Sweep Specialist",
        "Comeback from Injury",
      ],
      "Shubman Gill": [
        "Indian Player",
        "Right-Handed Batsman",
        "Current GT Captain",
        "Under-19 World Cup Winner",
        "Youngest Indian ODI Double Centurion",
      ],
      "Mohammed Shami": [
        "Indian Player",
        "Fast Bowler",
        "Current GT Player",
        "Most Wickets in 2023 World Cup",
        "Comeback from Injury",
      ],
      "Yuzvendra Chahal": [
        "Indian Player",
        "Leg-Spinner",
        "Current RR Player",
        "Former RCB Player",
        "Chess Player",
        "Most T20I Wickets for India",
        "YouTube Channel",
        "Married",
      ],
      "Suryakumar Yadav": [
        "Indian Player",
        "Right-Handed Batsman",
        "Current MI Player",
        "Current T20I Captain",
        "Mr. 360 Degrees",
        "Late International Debut",
        "Married",
      ],

      // Australian Players
      "Steve Smith": [
        "Australian Player",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Sandpaper Scandal",
        "Batting Average Above 60",
        "Married",
      ],
      "Pat Cummins": [
        "Australian Player",
        "Fast Bowler",
        "Current Test Captain",
        "Current ODI Captain",
        "Current SRH Captain",
        "Most Expensive IPL Buy 2024",
        "WTC Final Winner",
        "Married",
        "Has Children",
      ],
      "David Warner": [
        "Australian Player",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Former DC Captain",
        "Former SRH Captain",
        "Triple Century Scorer",
        "Sandpaper Scandal",
        "Retired from Tests",
        "Married",
        "Has Children",
        "TikTok Videos",
      ],
      "Mitchell Starc": [
        "Australian Player",
        "Left-Arm Fast Bowler",
        "Most Expensive IPL Buy 2024",
        "Current KKR Player",
        "Married to Cricketer",
        "Yorker Specialist",
      ],
      "Glenn Maxwell": [
        "Australian Player",
        "All-Rounder",
        "Current RCB Player",
        "Former PBKS Captain",
        "Big Show Nickname",
        "Reverse Sweep Specialist",
        "201* While Chasing",
        "Mental Health Advocate",
        "Married",
      ],
      "Adam Zampa": [
        "Australian Player",
        "Leg-Spinner",
        "Current RR Player",
        "Googly Specialist",
        "Married",
      ],
      "Marcus Stoinis": [
        "Australian Player",
        "All-Rounder",
        "Current LSG Player",
        "Greek Heritage",
      ],
      "Josh Hazlewood": [
        "Australian Player",
        "Fast Bowler",
        "Current RCB Player",
      ],
      "Travis Head": [
        "Australian Player",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Current SRH Player",
        "WTC Final Hero",
        "2023 World Cup Final Hero",
        "Married",
        "Has Children",
      ],

      // English Players
      "Joe Root": [
        "English Player",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Reverse Sweep Specialist",
        "Most Test Runs for England",
        "Married",
        "Has Children",
      ],
      "Ben Stokes": [
        "English Player",
        "All-Rounder",
        "Current Test Captain",
        "2019 World Cup Hero",
        "Headingley Hero",
        "New Zealand Born",
        "Married",
        "Has Children",
        "Bristol Incident",
      ],
      "Jos Buttler": [
        "English Player",
        "Wicket-Keeper Batsman",
        "Current RR Captain",
        "Current ODI Captain",
        "Current T20I Captain",
        "Mankading Incident",
        "Married",
        "Has Children",
      ],
      "Jonny Bairstow": [
        "English Player",
        "Wicket-Keeper Batsman",
        "Current PBKS Player",
        "Comeback from Injury",
        "100 Test Matches",
        "Married",
      ],
      "Mark Wood": [
        "English Player",
        "Fast Bowler",
        "Current LSG Player",
        "Express Pace",
        "Married",
        "Has Children",
      ],
      "Moeen Ali": [
        "English Player",
        "All-Rounder",
        "Off-Spinner",
        "Former CSK Player",
        "Retired from Tests",
        "Married",
        "Has Children",
      ],
      "Sam Curran": [
        "English Player",
        "All-Rounder",
        "Current PBKS Player",
        "Most Expensive IPL Buy 2023",
        "2022 T20 World Cup Player of Tournament",
        "Curran Brothers",
      ],

      // Pakistani Players
      "Babar Azam": [
        "Pakistani Player",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "Cover Drive Specialist",
      ],
      "Shaheen Afridi": [
        "Pakistani Player",
        "Left-Arm Fast Bowler",
        "Current T20I Captain",
        "Son-in-Law of Afridi",
        "Married",
      ],
      "Mohammad Rizwan": [
        "Pakistani Player",
        "Wicket-Keeper Batsman",
        "Current ODI Captain",
        "Current Test Captain",
        "Played from ICU",
      ],
      "Shadab Khan": [
        "Pakistani Player",
        "All-Rounder",
        "Leg-Spinner",
        "Googly Specialist",
      ],
      "Haris Rauf": [
        "Pakistani Player",
        "Fast Bowler",
        "BBL Discovery",
        "Tape Ball Background",
      ],
      "Fakhar Zaman": [
        "Pakistani Player",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Champions Trophy Hero",
        "Navy Background",
      ],
      "Naseem Shah": [
        "Pakistani Player",
        "Fast Bowler",
        "Youngest to Take Hat-trick",
        "Mother Passed Away",
      ],
      "Shahid Afridi": [
        "Pakistani Legend",
        "All-Rounder",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "Boom Boom",
        "Fastest ODI Century Record",
        "Most International Sixes",
        "Age Controversy",
        "Has Children",
      ],
      "Wasim Akram": [
        "Pakistani Legend",
        "Left-Arm Fast Bowler",
        "Sultan of Swing",
        "KKR Bowling Coach",
        "Diabetes Survivor",
        "Commentary Career",
        "Married Twice",
        "Has Children",
      ],
      "Shoaib Akhtar": [
        "Pakistani Legend",
        "Fast Bowler",
        "Fastest Ball Ever (161.3 kmph)",
        "Rawalpindi Express",
        "YouTube Cricket Analyst",
      ],

      // Other Notable Players
      "Kane Williamson": [
        "New Zealand Player",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "Former SRH Captain",
        "2019 World Cup Player of Tournament",
        "Married",
        "Has Children",
      ],
      "AB de Villiers": [
        "South African Legend",
        "Wicket-Keeper Batsman",
        "Mr. 360 Degrees",
        "Former RCB Player",
        "Former Test Captain",
        "Former ODI Captain",
        "Retired Early",
        "Fastest ODI 50, 100, 150",
        "Married",
        "Has Children",
      ],
      "Chris Gayle": [
        "West Indies Legend",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Universe Boss",
        "Most T20 Sixes",
        "Most T20 Centuries",
        "Former PBKS Player",
        "Former RCB Player",
        "Has Children",
      ],
      "Rashid Khan": [
        "Afghan Player",
        "Leg-Spinner",
        "Current GT Player",
        "Former SRH Player",
        "Youngest Captain",
        "Googly Specialist",
        "Age Controversy",
      ],
      "Shakib Al Hasan": [
        "Bangladeshi Player",
        "All-Rounder",
        "Left-Arm Spinner",
        "Current KKR Player",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "Political Figure",
        "Multiple Suspensions",
        "Married",
        "Has Children",
      ],
      "Trent Boult": [
        "New Zealand Player",
        "Left-Arm Fast Bowler",
        "Current RR Player",
        "Former MI Player",
        "Married",
        "Has Children",
      ],
      "Tim Southee": [
        "New Zealand Player",
        "Fast Bowler",
        "Current Test Captain",
        "Former KKR Player",
        "Married",
        "Has Children",
      ],
      "Quinton de Kock": [
        "South African Player",
        "Wicket-Keeper Batsman",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Current LSG Player",
        "Former MI Player",
        "Former Test Captain",
        "Former ODI Captain",
        "Retired from Tests",
        "Married",
        "Has Children",
      ],
      "Kagiso Rabada": [
        "South African Player",
        "Fast Bowler",
        "Current PBKS Player",
        "Former DC Player",
        "Fastest to 200 Test Wickets",
      ],

      // Legends
      "Don Bradman": [
        "Australian Legend",
        "Right-Handed Batsman",
        "Batting Average 99.94",
        "The Don",
        "Most Double Centuries",
        "Bodyline Target",
        "Invincibles Captain",
      ],
      "Viv Richards": [
        "West Indies Legend",
        "Right-Handed Batsman",
        "Master Blaster",
        "Never Wore Helmet",
        "Stadium Named After",
        "Former Test Captain",
        "Former ODI Captain",
      ],
      "Shane Warne": [
        "Australian Legend",
        "Leg-Spinner",
        "Ball of the Century",
        "700+ Test Wickets",
        "Former RR Captain",
        "RR Captain IPL Winner",
        "Commentary Career",
        "Died in 2022",
      ],
      "Brian Lara": [
        "West Indies Legend",
        "Left-Handed Batsman",
        "Highest Test Score 400*",
        "Prince of Trinidad",
        "First Class 501*",
        "Former Test Captain",
        "Former ODI Captain",
      ],
      "Jacques Kallis": [
        "South African Legend",
        "All-Rounder",
        "Right-Handed Batsman",
        "Former KKR Player",
        "Former Test Captain",
        "Former ODI Captain",
        "10000 Runs and 250 Wickets",
        "Married",
      ],
      "Muttiah Muralitharan": [
        "Sri Lankan Legend",
        "Off-Spinner",
        "Most Test Wickets",
        "Doosra Pioneer",
        "Bowling Action Controversy",
        "Former CSK Player",
        "Former SRH Bowling Coach",
        "Tamil Background",
        "Married",
      ],
      "Kumar Sangakkara": [
        "Sri Lankan Legend",
        "Wicket-Keeper Batsman",
        "Left-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Four Consecutive ODI Centuries",
        "MCC President",
        "Commentary Career",
        "Married",
        "Has Children",
      ],

      // Women Cricketers
      "Smriti Mandhana": [
        "Indian Women Player",
        "Left-Handed Batsman",
        "Left-Handed Opener",
        "Current RCB WPL Vice-Captain",
        "Former Indian Vice-Captain",
      ],
      "Harmanpreet Kaur": [
        "Indian Women Player",
        "Right-Handed Batsman",
        "All-Rounder",
        "Current ODI Captain",
        "Current T20I Captain",
        "Current MI WPL Captain",
        "171* vs Australia",
        "First Indian T20I Century",
      ],
      "Mithali Raj": [
        "Indian Women Legend",
        "Right-Handed Batsman",
        "Former Test Captain",
        "Former ODI Captain",
        "Most ODI Runs Women",
        "Biopic Made",
        "Retired in 2022",
      ],
      "Jhulan Goswami": [
        "Indian Women Legend",
        "Fast Bowler",
        "Most ODI Wickets Women",
        "Chakdaha Express",
        "Retired in 2022",
      ],
      "Ellyse Perry": [
        "Australian Women Player",
        "All-Rounder",
        "Fast Bowler",
        "Right-Handed Batsman",
        "Current RCB WPL Player",
        "Played Football and Cricket",
        "Dual International",
        "Married",
      ],
      "Meg Lanning": [
        "Australian Women Player",
        "Right-Handed Batsman",
        "Former Australian Captain",
        "Former Test Captain",
        "Former ODI Captain",
        "Former T20I Captain",
        "Current DC WPL Captain",
        "Mental Health Break",
      ],
      "Alyssa Healy": [
        "Australian Women Player",
        "Wicket-Keeper Batsman",
        "Right-Handed Batsman",
        "Current Australian Captain",
        "Current Test Captain",
        "Current ODI Captain",
        "Current T20I Captain",
        "Current UP WPL Captain",
        "Married to Starc",
      ],
    },

    tennis: {
      // Current Male Players
      "Novak Djokovic": [
        "Serbian Player",
        "Right-Handed",
        "24 Grand Slams Record",
        "Most Grand Slams Men",
        "Gluten-Free Diet",
        "Most Weeks at No. 1",
        "Former No. 1",
        "Career Golden Masters",
        "Double Career Slam",
        "Never Retired Mid-Match",
        "Married",
        "Has Children",
      ],
      "Carlos Alcaraz": [
        "Spanish Player",
        "Right-Handed",
        "Youngest Ever No. 1",
        "Current No. 1",
        "Coached by Ferrero",
        "Real Madrid Fan",
        "Wimbledon Champion",
        "US Open Champion",
        "Multiple Grand Slams",
      ],
      "Rafael Nadal": [
        "Spanish Player",
        "Left-Handed",
        "Left-Handed Natural Righty",
        "22 Grand Slams",
        "14 French Open Titles",
        "King of Clay",
        "Uncle Toni Coached",
        "Never Smashed Racquet",
        "Former No. 1",
        "Olympic Gold Medalist",
        "Married",
        "Has Children",
      ],
      "Daniil Medvedev": [
        "Russian Player",
        "Right-Handed",
        "Octopus Nickname",
        "US Open Champion",
        "Grand Slam Winner",
        "Chess Player",
        "Former No. 1",
        "Married",
      ],
      "Stefanos Tsitsipas": [
        "Greek Player",
        "Right-Handed",
        "One-Handed Backhand",
        "YouTube Vlogger",
        "Coached by Parent",
        "Monte Carlo Master",
        "Never Won Slam",
        "Multiple Slam Finals",
      ],
      "Alexander Zverev": [
        "German Player",
        "Right-Handed",
        "Olympic Gold Medalist",
        "ATP Finals Winner",
        "Multiple Masters Titles",
        "Domestic Violence Case",
        "Ankle Injury 2022",
        "Never Won Slam",
        "Former No. 2",
      ],
      "Andrey Rublev": [
        "Russian Player",
        "Right-Handed",
        "Bweh Celebration",
        "Masters 1000 Struggles",
        "Multiple Masters Finals",
      ],
      "Casper Ruud": [
        "Norwegian Player",
        "Right-Handed",
        "Clay Court Specialist",
        "Multiple Slam Finals",
        "Never Won Slam",
        "Golf Enthusiast",
        "Coached by Parent",
        "Former No. 2",
      ],
      "Jannik Sinner": [
        "Italian Player",
        "Right-Handed",
        "Coached by Cahill",
        "Australian Open Champion",
        "Grand Slam Winner",
        "Current No. 2",
        "Former No. 1",
        "Doping Case",
      ],
      "Holger Rune": [
        "Danish Player",
        "Right-Handed",
        "Mother on Tour",
        "Multiple Coaches",
        "Paris Master Winner",
        "Masters Champion",
        "Coached by Parent",
      ],
      "Taylor Fritz": [
        "American Player",
        "Right-Handed",
        "Top 10 Player",
        "Indian Wells Winner",
        "Masters Champion",
        "Son of Tennis Players",
        "Has Children",
      ],
      "Felix Auger-Aliassime": [
        "Canadian Player",
        "Right-Handed",
        "Uncle Toni Coached",
        "Davis Cup Hero",
        "Multiple ATP Titles",
        "Never Won Masters",
      ],

      // Recent Legends & Veterans
      "Roger Federer": [
        "Swiss Legend",
        "Right-Handed",
        "20 Grand Slams",
        "8 Wimbledon Titles",
        "One-Handed Backhand",
        "Never Retired Mid-Match",
        "Longest No. 1 Streak",
        "Former No. 1",
        "Twin Sets of Twins",
        "Met Gala Regular",
        "Retired in 2022",
        "Married",
        "Has Children",
      ],
      "Andy Murray": [
        "British Player",
        "Right-Handed",
        "3 Grand Slams",
        "Hip Replacement Player",
        "Ended 77-Year Drought",
        "Olympic Gold Medalist",
        "Former No. 1",
        "Married",
        "Has Children",
      ],
      "Stan Wawrinka": [
        "Swiss Player",
        "Right-Handed",
        "3 Grand Slams",
        "One-Handed Backhand",
        "Tattoo Quote",
        "Former No. 3",
      ],
      "Juan Martin del Potro": [
        "Argentine Player",
        "Right-Handed",
        "US Open Champion",
        "Grand Slam Winner",
        "Former No. 3",
      ],
      "Marin Cilic": [
        "Croatian Player",
        "Right-Handed",
        "US Open Champion",
        "Grand Slam Winner",
        "Former No. 3",
        "Married",
      ],
      "Dominic Thiem": [
        "Austrian Player",
        "Right-Handed",
        "US Open Champion",
        "Grand Slam Winner",
        "One-Handed Backhand",
        "Wrist Injury",
        "Former No. 3",
      ],
      "Nick Kyrgios": [
        "Australian Player",
        "Right-Handed",
        "Underarm Server",
        "Basketball Fan",
        "Mental Health Advocate",
        "Wimbledon Finalist",
        "Never Won Slam",
        "Assault Charges",
      ],
      "Gael Monfils": [
        "French Player",
        "Right-Handed",
        "La Monf Showman",
        "Married Svitolina",
        "Never Won Masters",
      ],

      // Women Current Players
      "Iga Swiatek": [
        "Polish Player",
        "Right-Handed",
        "Current No. 1",
        "Former No. 1",
        "Bagel Specialist",
        "4 French Open Titles",
        "Multiple Grand Slams",
        "Psychologist on Tour",
        "Most Weeks at No. 1 Active",
      ],
      "Aryna Sabalenka": [
        "Belarusian Player",
        "Right-Handed",
        "Australian Open Champion",
        "Grand Slam Winner",
        "Multiple Grand Slams",
        "Tiger Tattoo",
        "Former No. 1",
        "Current No. 2",
      ],
      "Coco Gauff": [
        "American Player",
        "Right-Handed",
        "US Open Champion",
        "Grand Slam Winner",
        "Beat Venus at 15",
        "New Balance Deal",
        "Social Activist",
      ],
      "Elena Rybakina": [
        "Kazakhstani Player",
        "Right-Handed",
        "Wimbledon Champion",
        "Grand Slam Winner",
        "Born in Russia",
        "Changed Nationality",
      ],
      "Jessica Pegula": [
        "American Player",
        "Right-Handed",
        "Billionaire Parents",
        "Skincare Line",
        "Never Won Slam",
        "Multiple Slam Quarters",
        "Married",
      ],
      "Ons Jabeur": [
        "Tunisian Player",
        "Right-Handed",
        "Minister of Happiness",
        "Arab Trailblazer",
        "Multiple Slam Finals",
        "Never Won Slam",
        "Wimbledon Finalist",
        "Married",
      ],
      "Maria Sakkari": [
        "Greek Player",
        "Right-Handed",
        "Never Won WTA 1000",
        "Multiple Slam Semis",
        "Never Won Slam",
      ],
      "Petra Kvitova": [
        "Czech Player",
        "Left-Handed",
        "2x Wimbledon Champion",
        "Grand Slam Winner",
        "Multiple Grand Slams",
        "Knife Attack Survivor",
        "Former No. 2",
      ],

      // Women Legends
      "Serena Williams": [
        "American Legend",
        "Right-Handed",
        "23 Grand Slams",
        "Most Grand Slams Open Era",
        "Pregnant Slam Win",
        "Sister Rivalry",
        "Fashion Designer",
        "Former No. 1",
        "Retired in 2022",
        "Married",
        "Has Children",
        "Olympic Gold Medalist",
      ],
      "Venus Williams": [
        "American Legend",
        "Right-Handed",
        "7 Grand Slams",
        "Sjögren's Syndrome",
        "Olympic Gold Medalist",
        "Sister Rivalry",
        "Still Active",
        "Former No. 1",
        "Fashion Designer",
        "EleVen Brand",
      ],
      "Steffi Graf": [
        "German Legend",
        "Right-Handed",
        "22 Grand Slams",
        "Golden Slam Winner",
        "Calendar Grand Slam",
        "Married Agassi",
        "377 Weeks No. 1",
        "Former No. 1",
        "Has Children",
      ],
      "Martina Navratilova": [
        "Czech-American Legend",
        "Left-Handed",
        "18 Grand Slams",
        "9 Wimbledon Titles",
        "LGBTQ Pioneer",
        "Former No. 1",
        "Commentary Career",
      ],
      "Maria Sharapova": [
        "Russian Legend",
        "Right-Handed",
        "5 Grand Slams",
        "Career Grand Slam",
        "Candy Business",
        "Meldonium Ban",
        "Former No. 1",
        "Retired in 2020",
      ],
      "Monica Seles": [
        "Yugoslav-American Legend",
        "Right-Handed",
        "9 Grand Slams",
        "Stabbing Victim",
        "Two-Handed Both Sides",
        "Former No. 1",
      ],
      "Li Na": [
        "Chinese Legend",
        "Right-Handed",
        "2 Grand Slams",
        "First Asian Slam Winner",
        "Tattoo Rose",
        "Retired in 2014",
        "Former No. 2",
        "Married",
        "Has Children",
      ],
      "Simona Halep": [
        "Romanian Player",
        "Right-Handed",
        "2 Grand Slams",
        "Doping Suspension",
        "Former No. 1",
        "French Open Champion",
        "Wimbledon Champion",
        "Married",
      ],

      // Special Players
      "John Isner": [
        "American Player",
        "Right-Handed",
        "Longest Match Player",
        "Never Won Masters",
        "Retired in 2023",
        "Married",
        "Has Children",
      ],
      "Bob Bryan": [
        "American Doubles Legend",
        "Left-Handed",
        "Twin Partner Mike",
        "Most Doubles Titles",
        "Grand Slam Doubles Champion",
        "Former No. 1 Doubles",
        "Retired in 2020",
        "Stanford Graduate",
        "Married",
        "Has Children",
      ],
      "Mike Bryan": [
        "American Doubles Legend",
        "Right-Handed",
        "Twin Partner Bob",
        "Most Grand Slam Doubles",
        "Grand Slam Doubles Champion",
        "Former No. 1 Doubles",
        "Retired in 2020",
        "Stanford Graduate",
        "Married",
        "Has Children",
      ],
    },

    f1: {
      // Current 2024 Grid
      "Max Verstappen": [
        "Dutch Driver",
        "Red Bull Racing",
        "Current Driver",
        "3x World Champion",
        "Youngest Race Winner",
        "Son of F1 Driver",
        "Sim Racing Expert",
        "19 Wins in 2023",
        "10 Consecutive Wins",
        "Monaco Resident",
      ],
      "Sergio Perez": [
        "Mexican Driver",
        "Red Bull Racing",
        "Current Driver",
        "Former Racing Point Driver",
        "Former McLaren Driver",
        "Married",
        "Has Children",
      ],
      "Lewis Hamilton": [
        "British Driver",
        "Mercedes AMG",
        "Current Driver",
        "7x World Champion",
        "Joint Most Championships",
        "Most Wins Ever",
        "Most Pole Positions",
        "Most Podiums Ever",
        "Only Black Driver",
        "Vegan",
        "Knighted by Queen",
        "Moving to Ferrari 2025",
        "Monaco Resident",
      ],
      "George Russell": [
        "British Driver",
        "Mercedes AMG",
        "Current Driver",
        "PowerPoint Presentations",
        "GPDA Director",
        "Former Williams Driver",
        "Mercedes Junior",
      ],
      "Charles Leclerc": [
        "Monégasque Driver",
        "Scuderia Ferrari",
        "Current Driver",
        "Monaco Curse",
        "Piano Player",
        "Lost Godfather",
        "Lost Father",
        "Youngest Ferrari Pole",
        "Ferrari Academy",
        "Monaco Resident",
      ],
      "Carlos Sainz Jr.": [
        "Spanish Driver",
        "Scuderia Ferrari",
        "Current Driver",
        "Rally Legend Son",
        "Golf Enthusiast",
        "Moving to Williams 2025",
        "Former McLaren Driver",
        "Former Renault Driver",
        "Former Toro Rosso Driver",
        "Madrid Native",
      ],
      "Lando Norris": [
        "British Driver",
        "McLaren F1",
        "Current Driver",
        "Twitch Streamer",
        "Quadrant CEO",
        "First Win Miami 2024",
        "McLaren Academy",
        "Monaco Resident",
      ],
      "Oscar Piastri": [
        "Australian Driver",
        "McLaren F1",
        "Current Driver",
        "Alpine Contract Drama",
        "F2 Champion",
        "F3 Champion",
        "Webber Managed",
        "Sprint Winner",
        "Alpine Academy",
      ],
      "Fernando Alonso": [
        "Spanish Driver",
        "Aston Martin",
        "Current Driver",
        "2x World Champion",
        "Oldest on Grid",
        "Kimoa Brand",
        "32 Race Wins",
        "Former Ferrari Driver",
        "Former McLaren Driver",
        "Former Renault Driver",
        "Former Alpine Driver",
        "Le Mans Winner",
        "Triple Crown Attempt",
      ],
      "Lance Stroll": [
        "Canadian Driver",
        "Aston Martin",
        "Current Driver",
        "Billionaire Dad Owns Team",
        "Youngest Rookie Podium",
        "Pole Position Turkey",
        "Former Williams Driver",
        "Former Racing Point Driver",
      ],
      "Pierre Gasly": [
        "French Driver",
        "Alpine F1",
        "Current Driver",
        "Monza Winner",
        "Former Red Bull Driver",
        "Former AlphaTauri Driver",
      ],
      "Esteban Ocon": [
        "French Driver",
        "Alpine F1",
        "Current Driver",
        "Hungary Winner",
        "Mercedes Junior",
        "Former Force India Driver",
        "Former Manor Driver",
      ],
      "Valtteri Bottas": [
        "Finnish Driver",
        "Stake F1 Sauber",
        "Current Driver",
        "Former Mercedes Driver",
        "10 Race Wins",
        "Coffee Business",
        "Married",
      ],
      "Zhou Guanyu": [
        "Chinese Driver",
        "Stake F1 Sauber",
        "Current Driver",
        "First Chinese F1 Driver",
        "Silverstone Crash Survivor",
        "Alfa Romeo Academy",
        "Alpine Academy",
      ],
      "Alex Albon": [
        "Thai-British Driver",
        "Williams Racing",
        "Current Driver",
        "Former Red Bull Driver",
        "Former Toro Rosso Driver",
        "Red Bull Reserve",
      ],
      "Logan Sargeant": [
        "American Driver",
        "Williams Racing",
        "Current Driver",
        "Only American on Grid",
        "First American Since 2015",
        "Williams Academy",
      ],
      "Kevin Magnussen": [
        "Danish Driver",
        "Haas F1",
        "Current Driver",
        "Son of F1 Driver",
        "Former McLaren Driver",
        "Former Renault Driver",
        "Married",
        "Has Children",
      ],
      "Nico Hulkenberg": [
        "German Driver",
        "Haas F1",
        "Current Driver",
        "No Podium Record",
        "Most Races Without Podium",
        "Le Mans Winner",
        "Moving to Sauber 2025",
        "Former Renault Driver",
        "Former Force India Driver",
        "Former Williams Driver",
      ],
      "Yuki Tsunoda": [
        "Japanese Driver",
        "RB Team",
        "Current Driver",
        "Shortest on Grid",
        "Lives in Italy",
        "Red Bull Junior",
        "Honda Protégé",
      ],
      "Daniel Ricciardo": [
        "Australian Driver",
        "RB Team",
        "Current Driver",
        "Honey Badger",
        "Shoey Inventor",
        "8 Race Wins",
        "Former Red Bull Driver",
        "Former McLaren Driver",
        "Former Renault Driver",
      ],

      // Legends
      "Michael Schumacher": [
        "German Legend",
        "Retired Driver",
        "7x World Champion",
        "Joint Most Championships",
        "91 Race Wins",
        "Ferrari Legend",
        "Skiing Accident",
        "Most Fastest Laps",
        "Former Mercedes Driver",
        "Former Benetton Driver",
        "Has Children",
      ],
      "Ayrton Senna": [
        "Brazilian Legend",
        "3x World Champion",
        "41 Race Wins",
        "Died at Imola 1994",
        "Monaco Master",
        "McLaren Legend",
      ],
      "Alain Prost": [
        "French Legend",
        "4x World Champion",
        "The Professor",
        "51 Race Wins",
        "Former Ferrari Driver",
        "Former McLaren Driver",
        "Former Williams Driver",
        "Former Renault Driver",
      ],
      "Niki Lauda": [
        "Austrian Legend",
        "3x World Champion",
        "Nürburgring Fire Survivor",
        "1976 Comeback",
        "Airline Owner",
        "Red Cap Icon",
        "Died in 2019",
        "Former Ferrari Driver",
        "Former McLaren Driver",
        "Mercedes Non-Executive Chairman",
      ],
      "Juan Manuel Fangio": [
        "Argentine Legend",
        "5x World Champion",
        "Oldest Champion",
        "Best Win Percentage",
        "1950s Era",
      ],
      "Jim Clark": [
        "Scottish Legend",
        "2x World Champion",
        "Lotus Legend",
        "Died at Hockenheim 1968",
        "Indy 500 Winner",
      ],
      "Jackie Stewart": [
        "Scottish Legend",
        "3x World Champion",
        "Safety Pioneer",
        "Dyslexia Advocate",
        "The Flying Scot",
        "TV Commentator",
      ],
      "Nelson Piquet": [
        "Brazilian Legend",
        "3x World Champion",
        "Former Brabham Driver",
        "Former Williams Driver",
        "Has Children",
      ],
      "Nigel Mansell": [
        "British Legend",
        "1992 World Champion",
        "Mustache Icon",
        "IndyCar Champion",
        "Former Ferrari Driver",
        "Former Williams Driver",
        "Former McLaren Driver",
      ],
      "Damon Hill": [
        "British Legend",
        "1996 World Champion",
        "Graham Hill's Son",
        "Sky Sports Pundit",
        "Former Williams Driver",
        "Former Jordan Driver",
      ],
      "Kimi Raikkonen": [
        "Finnish Legend",
        "Retired Driver",
        "2007 World Champion",
        "The Iceman",
        "Most Races Started",
        "Retired in 2021",
        "Former Ferrari Driver",
        "Former McLaren Driver",
        "Former Alfa Romeo Driver",
        "Married",
        "Has Children",
      ],
      "Jenson Button": [
        "British Legend",
        "Retired Driver",
        "2009 World Champion",
        "Brawn GP Champion",
        "Sky Sports Pundit",
        "Former McLaren Driver",
        "Former BAR Driver",
        "Married",
      ],
      "Sebastian Vettel": [
        "German Legend",
        "Retired Driver",
        "4x World Champion",
        "Youngest Champion",
        "Red Bull Domination",
        "Environmental Activist",
        "Retired in 2022",
        "Former Ferrari Driver",
        "Former Red Bull Driver",
        "Former Aston Martin Driver",
        "Married",
        "Has Children",
      ],
      "Mika Hakkinen": [
        "Finnish Legend",
        "2x World Champion",
        "The Flying Finn",
        "Former McLaren Driver",
      ],

      // Recent Drivers
      "Mick Schumacher": [
        "German Driver",
        "Michael's Son",
        "Former Haas Driver",
        "Mercedes Reserve",
        "Alpine WEC Driver",
        "Ferrari Academy",
        "F2 Champion",
      ],
      "Romain Grosjean": [
        "French Driver",
        "Bahrain Fire Survivor",
        "Phoenix Tattoo",
        "IndyCar Driver",
        "Former Haas Driver",
        "Former Lotus Driver",
        "Married",
        "Has Children",
      ],
      "Robert Kubica": [
        "Polish Driver",
        "Rally Accident Survivor",
        "Canada 2008 Winner",
        "Former BMW Driver",
        "Former Williams Driver",
      ],
    },

    tv: {
      // Castle Characters
      "Richard Castle": [
        "Castle Character",
        "Main Character",
        "Writer",
        "Mystery Novelist",
        "Single Dad",
        "Married",
        "Has Children",
        "NYPD Consultant",
        "Divorced",
        "Multiple Marriages",
      ],
      "Kate Beckett": [
        "Castle Character",
        "Main Character",
        "NYPD Detective",
        "Team Leader",
        "Stanford Graduate",
        "Married",
        "Undercover Experience",
        "NYPD Captain",
      ],
      "Alexis Castle": [
        "Castle Character",
        "Recurring Character",
        "Columbia Student",
        "Kidnapped in Paris",
        "Red Hair",
      ],
      "Martha Rodgers": [
        "Castle Character",
        "Recurring Character",
        "Broadway Actress",
        "Acting School Owner",
        "Multiple Marriages",
        "Has Children",
        "Red Hair",
      ],
      "Javier Esposito": [
        "Castle Character",
        "Main Character",
        "NYPD Detective",
        "Former Special Forces",
        "Partner to Ryan",
      ],
      "Kevin Ryan": [
        "Castle Character",
        "Main Character",
        "NYPD Detective",
        "Partner to Esposito",
        "Married",
        "Has Children",
        "Irish Descent",
        "Undercover Experience",
      ],
      "Lanie Parish": [
        "Castle Character",
        "Recurring Character",
        "Medical Examiner",
        "Medical School",
      ],
      "Roy Montgomery": [
        "Castle Character",
        "Recurring Character",
        "NYPD Captain",
        "Team Leader",
        "Died",
        "Married",
        "Has Children",
        "NYPD Detective",
      ],
      "Victoria Gates": [
        "Castle Character",
        "Recurring Character",
        "NYPD Captain",
        "Team Leader",
        "Iron Gates Nickname",
        "Replaced Montgomery",
        "Married",
        "NYPD Detective",
      ],
      "Jenny Ryan": [
        "Castle Character",
        "Recurring Character",
        "Married",
        "Has Children",
      ],
      "Jerry Tyson": [
        "Castle Character",
        "Main Antagonist",
        "Serial Killer",
        "Recurring Character",
        "Criminal",
        "Foster Kid",
        "Fake Death",
        "Died",
        "Jumps Off Bridge",
      ],
      "Senator Bracken": [
        "Castle Character",
        "Main Antagonist",
        "Criminal",
        "Recurring Character",
        "Married",
        "Died",
      ],

      // Dexter Characters
      "Dexter Morgan": [
        "Dexter Character",
        "Main Character",
        "Criminal",
        "Serial Killer",
        "Spouse Died",
        "Has Children",
        "Single Dad",
        "Fake Death",
      ],
      "Debra Morgan": [
        "Dexter Character",
        "Main Character",
        "Adopted",
        "Former Vice Detective",
        "Undercover Experience",
        "Died",
        "Addiction Struggle",
      ],
      "Rita Bennett": [
        "Dexter Character",
        "Recurring Character",
        "Married",
        "Spouse Died",
        "Multiple Marriages",
        "Died",
      ],
      "Vince Masuka": [
        "Dexter Character",
        "Main Character",
        "Medical Examiner",
        "Medical School",
      ],
      "Angel Batista": [
        "Dexter Character",
        "Main Character",
        "Married",
        "Divorced",
        "Has Children",
        "Single Dad",
      ],

      // The Mentalist Characters
      "Patrick Jane": [
        "Mentalist Character",
        "Main Character",
        "CBI Consultant",
        "Family Killed by Red John",
        "Tea Drinker",
        "Memory Palace",
        "Sleeps in Attic",
        "Married",
        "Con Artist",
        "Profiler",
        "Spouse Died",
        "Has Children",
        "Multiple Marriages",
        "Undercover Experience",
        "Night Terrors",
      ],
      "Teresa Lisbon": [
        "Mentalist Character",
        "Main Character",
        "CBI Agent",
        "Becomes FBI Agent",
        "Team Leader",
        "Catholic",
        "Raised Brothers After Parents Died",
        "Marries Jane",
        "Married",
        "Has Children",
        "Undercover Experience",
      ],
      "Kimball Cho": [
        "Mentalist Character",
        "Main Character",
        "CBI Agent",
        "Becomes FBI Agent",
        "Former Gang Member",
        "Team Leader",
        "Former Special Forces",
      ],
      "Grace Van Pelt": [
        "Mentalist Character",
        "Main Character",
        "CBI Agent",
        "Computer Expert",
        "Marries Rigsby",
        "Married",
        "Has Children",
        "Leaves CBI",
        "Red Hair",
        "Undercover Experience",
      ],
      "Wayne Rigsby": [
        "Mentalist Character",
        "Main Character",
        "CBI Agent",
        "Arson Specialist",
        "Marries Van Pelt",
        "Married",
        "Has Children",
        "Has Son Benjamin",
        "Leaves CBI",
        "Undercover Experience",
      ],
      "Red John": [
        "Mentalist Character",
        "Main Antagonist",
        "Serial Killer",
        "Sheriff Thomas McAllister",
        "Blake Association Leader",
        "Main Character",
        "Criminal",
        "Died",
      ],
      "JJ LaRoche": [
        "Mentalist Character",
        "Recurring Character",
        "CBI Agent",
        "Died",
      ],
      "Michelle Vega": [
        "Mentalist Character",
        "Main Character",
        "FBI Agent",
        "Died",
      ],

      // Blacklist Characters
      "Raymond Reddington": [
        "Blacklist Character",
        "Main Character",
        "Criminal",
        "The Concierge of Crime",
        "Naval Intelligence Past",
        "FBI Informant",
        "Undercover Experience",
      ],
      "Elizabeth Keen": [
        "Blacklist Character",
        "Main Character",
        "FBI Agent",
        "Profiler",
        "Fake Death",
        "Married",
        "Has Children",
        "Adopted",
        "Undercover Experience",
      ],
      "Donald Ressler": [
        "Blacklist Character",
        "Main Character",
        "FBI Agent",
        "Addiction Struggle",
        "Team Leader",
        "Undercover Experience",
      ],
      "Harold Cooper": [
        "Blacklist Character",
        "Main Character",
        "FBI Assistant Director",
        "Team Leader",
        "Task Force Leader",
        "Married",
        "Has Children",
        "FBI Agent",
      ],
      "Aram Mojtabai": [
        "Blacklist Character",
        "Main Character",
        "Computer Expert",
        "Undercover Experience",
        "FBI Agent",
      ],
      "Dembe Zuma": [
        "Blacklist Character",
        "Main Character",
        "Former Child Soldier",
        "FBI Agent",
        "Has Children",
        "Criminal",
        "Single Dad",
      ],
      "Tom Keen": [
        "Blacklist Character",
        "Main Character",
        "Adopted",
        "Died",
        "Killed by Ian Garvey",
        "Married",
        "Has Children",
        "Undercover Experience",
      ],
      "Samar Navabi": [
        "Blacklist Character",
        "Main Character",
        "Mossad Agent",
        "FBI Agent",
        "Undercover Experience",
      ],
      "Mr. Kaplan": [
        "Blacklist Character",
        "Recurring Character",
        "Cleaner",
        "Kate Nemec",
        "Jumps Off Bridge",
        "Criminal",
        "Fake Death",
        "Died",
      ],
      "Peter Kotsiopulos": [
        "Blacklist Character",
        "Recurring Character",
        "Main Antagonist",
        "Criminal",
        "Died",
      ],
      "Berlin": [
        "Blacklist Character",
        "Recurring Character",
        "Main Antagonist",
        "Criminal",
        "Has Children",
        "Single Dad",
        "Died",
      ],

      // SWAT Characters
      "Daniel Harrelson": [
        "SWAT Character",
        "Main Character",
        "Team Leader",
        "Married",
        "SWAT Officer",
        "Former Special Forces",
        "Has Children",
      ],
      "David Kay": [
        "SWAT Character",
        "Main Character",
        "Team Leader",
        "SWAT Officer",
        "Married",
        "Has Children",
        "Deacon Nickname",
        "Catholic",
      ],
      "Dominique Luca": [
        "SWAT Character",
        "Main Character",
        "SWAT Officer",
        "Third Generation SWAT",
        "Grandfather Was SWAT",
        "Food Truck Owner",
        "Undercover Experience",
      ],
      "Victor Tan": [
        "SWAT Character",
        "Main Character",
        "SWAT Officer",
        "Former Vice Detective",
      ],
      "Jim Street": [
        "SWAT Character",
        "Main Character",
        "SWAT Officer",
        "Foster Kid",
        "Mother in Prison",
        "Undercover Experience",
      ],
      "Christina Alonso": [
        "SWAT Character",
        "Main Character",
        "SWAT Officer",
        "First Female SWAT",
        "Left for Germany",
        "Undercover Experience",
      ],
      "Robert Hicks": [
        "SWAT Character",
        "Main Character",
        "SWAT Commander",
        "Team Leader",
        "SWAT Officer",
        "Spouse Died",
      ],
      "Nichelle Carmichael": [
        "SWAT Character",
        "Recurring Character",
        "Married",
        "Has Children",
      ],

      // White Collar Characters
      "Neal Caffrey": [
        "White Collar Character",
        "Main Character",
        "Con Artist",
        "Art Forger",
        "Criminal",
        "Anklet Tracker",
        "Fake Death",
        "Undercover Experience",
      ],
      "Peter Burke": [
        "White Collar Character",
        "Main Character",
        "FBI Agent",
        "Team Leader",
        "Married",
        "Dog Named Satchmo",
        "Undercover Experience",
      ],
      "Elizabeth Burke": [
        "White Collar Character",
        "Main Character",
        "Event Planner",
        "Married",
        "Dog Named Satchmo",
      ],
      "Mozzie": [
        "White Collar Character",
        "Main Character",
        "Con Artist",
        "Criminal",
        "Conspiracy Theorist",
        "Married",
        "Art Forger",
        "Foster Kid",
        "Adopted",
        "Undercover Experience",
      ],
      "Diana Berrigan": [
        "White Collar Character",
        "Main Character",
        "FBI Agent",
        "Has Girlfriend Christie",
        "Has Children",
        "Undercover Experience",
      ],
      "Clinton Jones": [
        "White Collar Character",
        "Main Character",
        "FBI Agent",
        "Harvard Law",
      ],
      "Sara Ellis": [
        "White Collar Character",
        "Recurring Character",
        "Undercover Experience",
      ],
      "Kate Moreau": [
        "White Collar Character",
        "Recurring Character",
        "Con Artist",
        "Criminal",
        "Died",
      ],
      "Matthew Keller": [
        "White Collar Character",
        "Recurring Character",
        "Main Antagonist",
        "Con Artist",
        "Criminal",
        "Art Forger",
        "Died",
      ],
      "Alex Hunter": [
        "White Collar Character",
        "Recurring Character",
        "Con Artist",
        "Criminal",
        "Art Forger",
      ],

      // Prodigal Son Characters
      "Malcolm Bright": [
        "Prodigal Son Character",
        "Main Character",
        "NYPD Consultant",
        "Profiler",
        "Night Terrors",
        "Hand Tremor",
        "Addiction Struggle",
      ],
      "Martin Whitly": [
        "Prodigal Son Character",
        "Main Character",
        "Serial Killer",
        "The Surgeon",
        "23 Victims",
        "Psychiatric Hospital",
        "Criminal",
        "Has Children",
      ],
      "Gil Arroyo": [
        "Prodigal Son Character",
        "Main Character",
        "NYPD Detective",
        "Team Leader",
        "Married",
        "Spouse Died",
      ],
      "Jessica Whitly": [
        "Prodigal Son Character",
        "Main Character",
        "Socialite",
        "Alcoholic",
        "Has Children",
        "Married",
      ],
      "Ainsley Whitly": [
        "Prodigal Son Character",
        "Main Character",
        "TV Reporter",
        "Kills Endicott",
      ],

      // The Recruit Characters
      "Owen Hendricks": [
        "The Recruit Character",
        "Main Character",
        "CIA Lawyer",
        "Georgetown Law",
        "Dragged Into Field Work",
        "Undercover Experience",
        "Grey Mail Threat",
      ],
      "Max Meladze": [
        "The Recruit Character",
        "Main Character",
        "Former Asset",
        "Criminal",
        "Grey Mail Threat",
        "Has Children",
        "Main Antagonist",
        "Died",
      ],
      "Hannah Copeland": ["The Recruit Character", "Recurring Character"],
    },
  },

  gameCategories: {
    cricket: [
      // Nationalities & Background
      "Indian Player",
      "Australian Player",
      "English Player",
      "Pakistani Player",
      "South African Player",
      "West Indies Player",
      "New Zealand Player",
      "Sri Lankan Player",
      "Bangladeshi Player",
      "Afghan Player",
      "West Indies Legend",
      "Australian Legend",
      "Pakistani Legend",
      "South African Legend",
      "Sri Lankan Legend",
      "Indian Women Player",
      "Australian Women Player",
      "Indian Women Legend",

      // Batting Styles & Positions
      "Right-Handed Batsman",
      "Left-Handed Batsman",
      "Left-Handed Opener",
      "Wicket-Keeper Batsman",

      // Batting Techniques
      "Cover Drive Specialist",
      "Pull Shot Specialist",
      "Reverse Sweep Specialist",
      "Helicopter Shot Creator",
      "Mr. 360 Degrees",
      "Yorker Specialist",

      // Batting Records
      "First to 100 International Centuries",
      "Only Player with 3 ODI Double Centuries",
      "Highest Individual ODI Score (264)",
      "First ODI Double Century Scorer",
      "Most Runs in International Cricket",
      "Scored 13000+ ODI Runs",
      "Most International Centuries While Chasing",
      "Triple Century Scorer",
      "Highest Test Score 400*",
      "Batting Average 99.94",
      "Most Double Centuries",
      "Youngest Indian ODI Double Centurion",
      "Batting Average Above 60",
      "First Indian T20I Century",
      "Most T20 Sixes",
      "Most T20 Centuries",
      "Fastest ODI 50, 100, 150",
      "Four Consecutive ODI Centuries",
      "Most Test Runs for England",
      "201* While Chasing",
      "171* vs Australia",
      "2023 World Cup Final Hero",
      "Most ODI Runs Women",
      "Fastest Indian T20I Century",
      "First Class 501*",

      // Bowling Types
      "Fast Bowler",
      "Left-Arm Fast Bowler",
      "Off-Spinner",
      "Left-Arm Spinner",
      "Leg-Spinner",
      "Express Pace",
      "Googly Specialist",
      "Carrom Ball Specialist",

      // Bowling Records
      "Fastest Ball Ever (161.3 kmph)",
      "Most Test Wickets",
      "Most ODI Wickets Women",
      "Most Wickets in 2023 World Cup",
      "Most 5-Wicket Hauls for India",
      "Most T20I Wickets for India",
      "Fastest Indian to 100 ODI Wickets",
      "Fastest to 200 Test Wickets",
      "Most Wickets in WTC",
      "700+ Test Wickets",
      "Youngest to Take Hat-trick",
      "Ball of the Century",

      // All-Round & Fielding
      "All-Rounder",
      "Fast-Bowling All-Rounder",
      "Most Stumpings in Career",
      "10000 Runs and 250 Wickets",

      // Current Teams
      "Current CSK Player",
      "Current MI Player",
      "Current MI Captain",
      "Current RCB Player",
      "Current KKR Player",
      "Current GT Player",
      "Current GT Captain",
      "Current DC Captain",
      "Current SRH Player",
      "Current SRH Captain",
      "Current PBKS Player",
      "Current RR Player",
      "Current RR Captain",
      "Current LSG Player",
      "Current LSG Captain",
      "Current MI WPL Captain",
      "Current RCB WPL Vice-Captain",
      "Current DC WPL Captain",
      "Current UP WPL Captain",

      // Former Teams
      "Former CSK Captain",
      "Former CSK Player",
      "Former MI Player",
      "Former RCB Player",
      "Former KKR Player",
      "Former GT Captain",
      "Former DC Captain",
      "Former SRH Captain",
      "Former SRH Player",
      "Former PBKS Player",
      "Former PBKS Captain",
      "Former RR Captain",
      "Former RR Player",
      "Former SRH Bowling Coach",
      "Former Indian Vice-Captain",

      // IPL Achievements
      "RCB Player Never Won IPL",
      "GT Captain First Season Win",
      "Orange Cap Winner",
      "Most Expensive IPL Buy 2023",
      "Most Expensive IPL Buy 2024",
      "RR Captain IPL Winner",

      // International Captaincy
      "Current Test Captain",
      "Current ODI Captain",
      "Current T20I Captain",
      "Former Test Captain",
      "Former ODI Captain",
      "Former T20I Captain",
      "Former Australian Captain",
      "Youngest Captain",
      "Current Test Vice-Captain",
      "Current Australian Captain",

      // Career Milestones
      "Retired Legend",
      "Retired Early",
      "Retired in 2022",
      "Retired from Tests",
      "200 Test Matches Played",
      "100 Test Matches",
      "Played 6 World Cups",
      "Died in 2022",
      "Late International Debut",
      "Dual International",
      "Mental Health Break",

      // World Cup & Championships
      "2011 World Cup Winning Captain",
      "2007 T20 WC Winner",
      "2019 World Cup Player of Tournament",
      "Champions Trophy Hero",
      "WTC Final Winner",
      "WTC Final Hero",
      "Under-19 World Cup Winner",
      "2019 World Cup Hero",
      "Headingley Hero",
      "2022 T20 World Cup Player of Tournament",

      // Nicknames
      "Hitman Nickname",
      "The Don",
      "Sir Jadeja Nickname",
      "Big Show Nickname",
      "Universe Boss",
      "Master Blaster",
      "Sultan of Swing",
      "Rawalpindi Express",
      "Boom Boom",
      "Prince of Trinidad",
      "Chakdaha Express",

      // Unique Facts
      "Sandpaper Scandal",
      "Age Controversy",
      "Fastest ODI Century Record",
      "Mankading Incident",
      "Never Wore Helmet",
      "Stadium Named After",
      "Invincibles Captain",
      "Bodyline Target",
      "MCC President",
      "Multiple Suspensions",
      "Doosra Pioneer",
      "Bowling Action Controversy",
      "Curran Brothers",

      // Professional Background
      "Lieutenant Colonel in Army",
      "Engineer Turned Cricketer",
      "YouTube Cricket Analyst",
      "Commentary Career",
      "KKR Bowling Coach",
      "Political Figure",
      "New Zealand Born",
      "YouTube Channel",
      "TikTok Videos",
      "Biopic Made",

      // Personal Life
      "Car Accident Survivor",
      "Comeback from Surgery",
      "Comeback from Injury",
      "Played from ICU",
      "Sword Celebration",
      "Chess Player",
      "Married to Cricketer",
      "Son-in-Law of Afridi",
      "Diabetes Survivor",
      "Mother Passed Away",
      "Navy Background",
      "Tape Ball Background",
      "BBL Discovery",
      "Tamil Background",
      "Played Football and Cricket",
      "Married to Starc",
      "Married",
      "Has Children",
      "Married to Actress",
      "Married to Presenter",
      "Mental Health Advocate",
      "Greek Heritage",
      "Bristol Incident",
      "Married Twice",
    ],

    tennis: [
      // Nationalities
      "Serbian Player",
      "Spanish Player",
      "Swiss Player",
      "Swiss Legend",
      "Russian Player",
      "Greek Player",
      "German Player",
      "Norwegian Player",
      "Italian Player",
      "Austrian Player",
      "Croatian Player",
      "Argentine Player",
      "Polish Player",
      "Belarusian Player",
      "American Player",
      "American Legend",
      "British Player",
      "French Player",
      "Canadian Player",
      "Danish Player",
      "Kazakhstani Player",
      "Tunisian Player",
      "Czech Player",
      "German Legend",
      "Czech-American Legend",
      "Australian Legend",
      "Yugoslav-American Legend",
      "Romanian Player",
      "Chinese Legend",
      "American Doubles Legend",
      "Russian Legend",

      // Grand Slam Achievements
      "24 Grand Slams Record",
      "23 Grand Slams",
      "22 Grand Slams",
      "20 Grand Slams",
      "14 French Open Titles",
      "8 Wimbledon Titles",
      "9 Wimbledon Titles",
      "7 Grand Slams",
      "5 Grand Slams",
      "4 French Open Titles",
      "3 Grand Slams",
      "2 Grand Slams",
      "2x Wimbledon Champion",
      "9 Grand Slams",
      "18 Grand Slams",
      "Multiple Grand Slams",
      "Grand Slam Winner",
      "Multiple Slam Finals",
      "Multiple Slam Quarters",
      "Never Won Slam",
      "Golden Slam Winner",
      "Calendar Grand Slam",
      "Career Grand Slam",
      "Career Golden Masters",
      "Double Career Slam",
      "First Asian Slam Winner",
      "Pregnant Slam Win",
      "Wimbledon Champion",
      "US Open Champion",
      "Australian Open Champion",
      "French Open Champion",
      "Olympic Gold Medalist",
      "Wimbledon Finalist",
      "Most Grand Slams Men",
      "Most Grand Slams Open Era",

      // Playing Styles
      "Right-Handed",
      "Left-Handed",
      "One-Handed Backhand",
      "Left-Handed Natural Righty",
      "Clay Court Specialist",
      "Two-Handed Both Sides",
      "Underarm Server",

      // Rankings & Records
      "Youngest Ever No. 1",
      "Most Weeks at No. 1",
      "377 Weeks No. 1",
      "Longest No. 1 Streak",
      "Current No. 1",
      "Current No. 2",
      "Former No. 1",
      "Former No. 2",
      "Former No. 3",
      "Most Weeks at No. 1 Active",
      "Most Grand Slam Doubles",
      "Most Doubles Titles",
      "Top 10 Player",
      "Longest Match Player",
      "Beat Venus at 15",
      "Never Retired Mid-Match",
      "Never Won WTA 1000",
      "Never Won Masters",
      "Paris Master Winner",
      "Masters Champion",
      "Multiple Masters Titles",
      "Multiple Masters Finals",
      "ATP Finals Winner",
      "Monte Carlo Master",
      "Indian Wells Winner",
      "Masters 1000 Struggles",
      "Former No. 1 Doubles",
      "Grand Slam Doubles Champion",
      "Stanford Graduate",
      "Most Prize Money",

      // Personal Facts
      "Gluten-Free Diet",
      "Never Smashed Racquet",
      "YouTube Vlogger",
      "Fashion Designer",
      "Candy Business",
      "Skincare Line",
      "Social Activist",
      "LGBTQ Pioneer",
      "Mental Health Advocate",
      "Psychologist on Tour",
      "Bweh Celebration",
      "Real Madrid Fan",
      "Chess Player",
      "Golf Enthusiast",
      "Basketball Fan",
      "EleVen Brand",
      "Commentary Career",
      "Octopus Nickname",
      "La Monf Showman",
      "King of Clay",
      "Minister of Happiness",
      "Bagel Specialist",
      "The Professor",

      // Relationships & Coaching
      "Uncle Toni Coached",
      "Coached by Ferrero",
      "Coached by Parent",
      "Coached by Cahill",
      "Twin Sets of Twins",
      "Twin Partner Mike",
      "Twin Partner Bob",
      "Married Agassi",
      "Sister Rivalry",
      "Married Svitolina",
      "Billionaire Parents",
      "Son of Tennis Players",
      "Changed Nationality",
      "Born in Russia",
      "Arab Trailblazer",
      "Mother on Tour",
      "Multiple Coaches",
      "Married",
      "Has Children",

      // Medical & Career Events
      "Hip Replacement Player",
      "Knife Attack Survivor",
      "Stabbing Victim",
      "Meldonium Ban",
      "Doping Suspension",
      "Doping Case",
      "Sjögren's Syndrome",
      "Ended 77-Year Drought",
      "Domestic Violence Case",
      "Assault Charges",
      "Ankle Injury 2022",
      "Wrist Injury",
      "Still Active",
      "Retired in 2020",
      "Retired in 2022",
      "Retired in 2023",
      "Retired in 2014",
      "Davis Cup Hero",
      "Tiger Tattoo",
      "Tattoo Quote",
      "Tattoo Rose",
      "New Balance Deal",
      "Met Gala Regular",
    ],

    f1: [
      // Nationalities
      "Dutch Driver",
      "British Driver",
      "Monégasque Driver",
      "Spanish Driver",
      "Mexican Driver",
      "Australian Driver",
      "French Driver",
      "Finnish Driver",
      "German Driver",
      "Chinese Driver",
      "Thai-British Driver",
      "American Driver",
      "Danish Driver",
      "Japanese Driver",
      "Canadian Driver",
      "German Legend",
      "Brazilian Legend",
      "French Legend",
      "Austrian Legend",
      "Argentine Legend",
      "Scottish Legend",
      "British Legend",
      "Finnish Legend",
      "Retired Driver",
      "Current Driver",

      // Current Teams (2024)
      "Red Bull Racing",
      "Mercedes AMG",
      "Scuderia Ferrari",
      "McLaren F1",
      "Alpine F1",
      "Aston Martin",
      "RB Team",
      "Stake F1 Sauber",
      "Williams Racing",
      "Haas F1",

      // Championships & Wins
      "3x World Champion",
      "4x World Champion",
      "7x World Champion",
      "2x World Champion",
      "1992 World Champion",
      "1996 World Champion",
      "2007 World Champion",
      "2009 World Champion",
      "Joint Most Championships",
      "91 Race Wins",
      "51 Race Wins",
      "41 Race Wins",
      "32 Race Wins",
      "10 Race Wins",
      "8 Race Wins",
      "Most Wins Ever",
      "19 Wins in 2023",
      "10 Consecutive Wins",
      "Youngest Race Winner",
      "Oldest Champion",
      "Youngest Champion",
      "Canada 2008 Winner",
      "Monza Winner",
      "Hungary Winner",
      "First Win Miami 2024",
      "Indy 500 Winner",
      "Triple Crown Attempt",

      // Records & Achievements
      "Most Pole Positions",
      "Most Podiums Ever",
      "Youngest Ferrari Pole",
      "Most Races Started",
      "Most Races Without Podium",
      "No Podium Record",
      "Youngest Rookie Podium",
      "Pole Position Turkey",
      "Best Win Percentage",
      "First American Since 2015",
      "First Chinese F1 Driver",
      "Le Mans Winner",
      "F2 Champion",
      "F3 Champion",
      "Sprint Winner",
      "Most Fastest Laps",
      "IndyCar Champion",
      "Brawn GP Champion",
      "1950s Era",
      "Alpine Academy",
      "McLaren Academy",
      "Ferrari Academy",
      "Red Bull Junior",
      "Mercedes Junior",
      "Williams Academy",
      "Alfa Romeo Academy",

      // Personal Facts
      "Son of F1 Driver",
      "Rally Legend Son",
      "Michael's Son",
      "Graham Hill's Son",
      "Billionaire Dad Owns Team",
      "Lost Godfather",
      "Lost Father",
      "Only Black Driver",
      "Only American on Grid",
      "Oldest on Grid",
      "Shortest on Grid",
      "Lives in Italy",
      "Monaco Resident",
      "Madrid Native",
      "Vegan",
      "Knighted by Queen",
      "Piano Player",
      "Golf Enthusiast",
      "Married",
      "Has Children",
      "Sim Racing Expert",
      "Twitch Streamer",
      "Quadrant CEO",
      "Kimoa Brand",
      "Coffee Business",
      "Environmental Activist",
      "PowerPoint Presentations",
      "GPDA Director",
      "Webber Managed",
      "Honda Protégé",
      "Sky Sports Pundit",
      "TV Commentator",
      "Phoenix Tattoo",
      "1976 Comeback",

      // Nicknames
      "Honey Badger",
      "The Iceman",
      "The Professor",
      "El Maestro",
      "The Flying Scot",
      "The Flying Finn",
      "Mustache Icon",
      "Shoey Inventor",
      "Red Cap Icon",

      // Career Events
      "Moving to Ferrari 2025",
      "Moving to Williams 2025",
      "Moving to Sauber 2025",
      "Alpine Contract Drama",
      "Red Bull Domination",
      "Mercedes Non-Executive Chairman",

      // Accidents & Safety
      "Skiing Accident",
      "Died at Imola 1994",
      "Died at Hockenheim 1968",
      "Nürburgring Fire Survivor",
      "Bahrain Fire Survivor",
      "Rally Accident Survivor",
      "Silverstone Crash Survivor",
      "Died in 2019",
      "Retired in 2021",
      "Retired in 2022",
      "Safety Pioneer",
      "Dyslexia Advocate",

      // Team History
      "Former Red Bull Driver",
      "Former Mercedes Driver",
      "Former Williams Driver",
      "Former Haas Driver",
      "Former AlphaTauri Driver",
      "Former Ferrari Driver",
      "Former McLaren Driver",
      "Former Renault Driver",
      "Former Alpine Driver",
      "Former Toro Rosso Driver",
      "Former Racing Point Driver",
      "Former Force India Driver",
      "Former Manor Driver",
      "Former Benetton Driver",
      "Former Brabham Driver",
      "Former BAR Driver",
      "Former BMW Driver",
      "Former Jordan Driver",
      "Former Alfa Romeo Driver",
      "Former Lotus Driver",
      "Ferrari Legend",
      "McLaren Legend",
      "Lotus Legend",
      "Monaco Curse",
      "Monaco Master",
      "Mercedes Reserve",
      "Red Bull Reserve",
      "Alpine WEC Driver",
      "IndyCar Driver",
    ],

    tv: [
      // Show Affiliations (7 categories)
      "Castle Character",
      "Mentalist Character",
      "Blacklist Character",
      "SWAT Character",
      "White Collar Character",
      "Prodigal Son Character",
      "The Recruit Character",

      // Character Types & Roles (26 categories)
      "Main Character",
      "Recurring Character",
      "Main Antagonist",
      "Writer",
      "NYPD Detective",
      "CBI Consultant",
      "CBI Agent",
      "FBI Agent",
      "CIA Lawyer",
      "SWAT Officer",
      "Con Artist",
      "Criminal",
      "Criminal Mastermind",
      "Serial Killer",
      "NYPD Consultant",
      "Team Leader",
      "NYPD Captain",
      "FBI Assistant Director",
      "SWAT Commander",
      "Event Planner",
      "Medical Examiner",
      "TV Reporter",
      "Broadway Actress",
      "Mystery Novelist",
      "Profiler",
      "Computer Expert",
      "Cleaner",
      "Former Asset",
      "Arson Specialist",
      "Art Forger",
      "Socialite",
      "The Surgeon",
      "The Concierge of Crime",
      "Acting School Owner",
      "Food Truck Owner",

      // Character Relationships (14 categories)
      "Partner to Ryan",
      "Partner to Esposito",
      "Marries Jane",
      "Marries Van Pelt",
      "Marries Rigsby",
      "Married",
      "Spouse Died",
      "Has Children",
      "Divorced",
      "Single Dad",
      "Foster Kid",
      "Adopted",
      "Multiple Marriages",
      "Has Son Benjamin",
      "Has Girlfriend Christie",

      // Education & Background (16 categories)
      "Stanford Graduate",
      "Columbia Student",
      "Medical School",
      "Georgetown Law",
      "Harvard Law",
      "Former Special Forces",
      "Former Gang Member",
      "Former Child Soldier",
      "Mossad Agent",
      "Naval Intelligence Past",
      "Former Vice Detective",
      "Undercover Experience",
      "Third Generation SWAT",
      "Grandfather Was SWAT",
      "Mother in Prison",
      "Irish Descent",

      // Personal Traits (14 categories)
      "Red Hair",
      "Tea Drinker",
      "Dog Named Satchmo",
      "Anklet Tracker",
      "Night Terrors",
      "Hand Tremor",
      "Catholic",
      "Alcoholic",
      "Iron Gates Nickname",
      "Deacon Nickname",
      "Memory Palace",
      "Sleeps in Attic",
      "Conspiracy Theorist",
      "First Female SWAT",

      // Story Events (22 categories)
      "Became Captain",
      "Kidnapped in Paris",
      "Family Killed by Red John",
      "Raised Brothers After Parents Died",
      "Leaves CBI",
      "Becomes FBI Agent",
      "Fake Death",
      "Killed by Ian Garvey",
      "Died",
      "Jumps Off Bridge",
      "Left for Germany",
      "Kills Endicott",
      "Grey Mail Threat",
      "Replaced Montgomery",
      "Sheriff Thomas McAllister",
      "Blake Association Leader",
      "Addiction Struggle",
      "Dragged Into Field Work",
      "Kate Nemec",
      "23 Victims",
      "FBI Informant",
      "Burke Premiere Events",
    ],
  },
};