// Game Data Configuration File
// Edit this file to add/remove players, characters, and categories

window.GAME_DATA = {
    playerMatches: {
        cricket: {
            'Virat Kohli': ['Indian Player', 'Right-Handed Batsman', 'Test Captain', 'Royal Challengers Bangalore', 'Scored 10000+ Runs'],
            'MS Dhoni': ['Indian Player', 'Wicket-Keeper', 'Chennai Super Kings', 'World Cup Winner', 'Test Captain'],
            'Rohit Sharma': ['Indian Player', 'Right-Handed Batsman', 'Mumbai Indians', 'ODI Specialist', 'T20 Specialist'],
            'Sachin Tendulkar': ['Indian Player', 'Right-Handed Batsman', 'Retired Player', 'Scored 10000+ Runs'],
            'Babar Azam': ['Pakistani Player', 'Right-Handed Batsman', 'Test Captain', 'ODI Specialist'],
            'Kane Williamson': ['New Zealand Player', 'Right-Handed Batsman', 'Test Captain', 'Sunrisers Hyderabad'],
            'Steve Smith': ['Australian Player', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Joe Root': ['English Player', 'Right-Handed Batsman', 'Test Captain', 'Test Match Specialist'],
            'Ben Stokes': ['English Player', 'All-Rounder', 'Left-Handed Batsman', 'Test Match Specialist'],
            'Jasprit Bumrah': ['Indian Player', 'Fast Bowler', 'Mumbai Indians', 'Bowled 150+ kmph'],
            'Pat Cummins': ['Australian Player', 'Fast Bowler', 'Test Captain', 'Bowled 150+ kmph'],
            'Trent Boult': ['New Zealand Player', 'Fast Bowler', 'Left-Handed Batsman'],
            'Kagiso Rabada': ['South African Player', 'Fast Bowler', 'Bowled 150+ kmph', 'Delhi Capitals'],
            'Rashid Khan': ['Afghan Player', 'Spinner', 'T20 Specialist', 'Sunrisers Hyderabad'],
            'Andre Russell': ['West Indies Player', 'All-Rounder', 'T20 Specialist', 'Kolkata Knight Riders'],
            'AB de Villiers': ['South African Player', 'Right-Handed Batsman', 'Retired Player', 'Royal Challengers Bangalore'],
            'David Warner': ['Australian Player', 'Left-Handed Batsman', 'Sunrisers Hyderabad', 'T20 Specialist'],
            'Jos Buttler': ['English Player', 'Wicket-Keeper', 'Right-Handed Batsman', 'Rajasthan Royals'],
            'Eoin Morgan': ['English Player', 'Left-Handed Batsman', 'World Cup Winner', 'Kolkata Knight Riders'],
            'Quinton de Kock': ['South African Player', 'Wicket-Keeper', 'Left-Handed Batsman'],
            'Lasith Malinga': ['Sri Lankan Player', 'Fast Bowler', 'Right-Handed Batsman', 'Retired Player', 'Mumbai Indians'],
            'Faf du Plessis': ['South African Player', 'Right-Handed Batsman', 'Chennai Super Kings', 'Test Match Specialist'],
            'Glenn Maxwell': ['Australian Player', 'All-Rounder', 'Right-Handed Batsman', 'Royal Challengers Bangalore'],
            'KL Rahul': ['Indian Player', 'Wicket-Keeper', 'Right-Handed Batsman', 'Punjab Kings'],
            'Rishabh Pant': ['Indian Player', 'Wicket-Keeper', 'Left-Handed Batsman', 'Delhi Capitals'],
            'Hardik Pandya': ['Indian Player', 'All-Rounder', 'Right-Handed Batsman', 'Mumbai Indians'],
            'Ravindra Jadeja': ['Indian Player', 'All-Rounder', 'Left-Handed Batsman', 'Chennai Super Kings', 'Spinner'],
            'R Ashwin': ['Indian Player', 'Spinner', 'All-Rounder', 'Test Match Specialist'],
            'Mohammad Rizwan': ['Pakistani Player', 'Wicket-Keeper', 'Right-Handed Batsman', 'T20 Specialist'],
            'Shaheen Afridi': ['Pakistani Player', 'Fast Bowler', 'Left-Handed Batsman', 'Bowled 150+ kmph'],
            'Mohammad Hafeez': ['Pakistani Player', 'All-Rounder', 'Right-Handed Batsman', 'Spinner'],
            'Shoaib Malik': ['Pakistani Player', 'All-Rounder', 'Right-Handed Batsman', 'T20 Specialist'],
            'Fakhar Zaman': ['Pakistani Player', 'Left-Handed Batsman', 'ODI Specialist'],
            'Mohammad Amir': ['Pakistani Player', 'Fast Bowler', 'Left-Handed Batsman', 'Bowled 150+ kmph'],
            'Shakib Al Hasan': ['Bangladeshi Player', 'All-Rounder', 'Left-Handed Batsman', 'Spinner'],
            'Mushfiqur Rahim': ['Bangladeshi Player', 'Wicket-Keeper', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Tamim Iqbal': ['Bangladeshi Player', 'Left-Handed Batsman', 'ODI Specialist', 'Test Match Specialist'],
            'Mustafizur Rahman': ['Bangladeshi Player', 'Fast Bowler', 'Left-Handed Batsman', 'T20 Specialist'],
            'Angelo Mathews': ['Sri Lankan Player', 'All-Rounder', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Dinesh Chandimal': ['Sri Lankan Player', 'Wicket-Keeper', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Thisara Perera': ['Sri Lankan Player', 'All-Rounder', 'Left-Handed Batsman', 'T20 Specialist'],
            'Tim Southee': ['New Zealand Player', 'Fast Bowler', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Mitchell Starc': ['Australian Player', 'Fast Bowler', 'Left-Handed Batsman', 'Bowled 150+ kmph'],
            'Josh Hazlewood': ['Australian Player', 'Fast Bowler', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Aaron Finch': ['Australian Player', 'Right-Handed Batsman', 'T20 Specialist', 'ODI Specialist'],
            'Marnus Labuschagne': ['Australian Player', 'Right-Handed Batsman', 'Test Match Specialist'],
            'Travis Head': ['Australian Player', 'Left-Handed Batsman', 'Test Match Specialist'],
            'Mitchell Marsh': ['Australian Player', 'All-Rounder', 'Right-Handed Batsman', 'Fast Bowler'],
            'Marcus Stoinis': ['Australian Player', 'All-Rounder', 'Right-Handed Batsman', 'Fast Bowler'],
            'Adam Zampa': ['Australian Player', 'Spinner', 'Right-Handed Batsman', 'T20 Specialist'],
            'Chris Gayle': ['West Indies Player', 'Left-Handed Batsman', 'T20 Specialist', 'Retired Player'],
            'Kieron Pollard': ['West Indies Player', 'All-Rounder', 'Right-Handed Batsman', 'Mumbai Indians'],
            'Dwayne Bravo': ['West Indies Player', 'All-Rounder', 'Right-Handed Batsman', 'Chennai Super Kings'],
            'Sunil Narine': ['West Indies Player', 'Spinner', 'Left-Handed Batsman', 'Kolkata Knight Riders'],
            'Nicholas Pooran': ['West Indies Player', 'Wicket-Keeper', 'Left-Handed Batsman', 'Punjab Kings']
        },

        tennis: {
            'Novak Djokovic': ['Serbian Player', 'Multiple Grand Slams', 'Former World No. 1', 'Australian Open Champion', 'Wimbledon Champion', 'Right-Handed Player', 'Hard Court Specialist'],
            'Rafael Nadal': ['Spanish Player', 'Multiple Grand Slams', 'Former World No. 1', 'French Open Champion', 'Clay Court Specialist', 'Left-Handed Player'],
            'Roger Federer': ['Swiss Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'Grass Court Specialist', 'Right-Handed Player', 'Retired Player', 'One-Handed Backhand'],
            'Carlos Alcaraz': ['Spanish Player', 'Grand Slam Winner', 'Former World No. 1', 'US Open Champion', 'Under 25 Years Old', 'Right-Handed Player'],
            'Daniil Medvedev': ['Russian Player', 'Grand Slam Winner', 'Former World No. 1', 'US Open Champion', 'Hard Court Specialist', 'Right-Handed Player'],
            'Stefanos Tsitsipas': ['Greek Player', 'Right-Handed Player', 'Hard Court Specialist', 'One-Handed Backhand', 'Under 25 Years Old'],
            'Alexander Zverev': ['German Player', 'Olympic Gold Medalist', 'Right-Handed Player', 'Hard Court Specialist'],
            'Andrey Rublev': ['Russian Player', 'Right-Handed Player', 'Hard Court Specialist', 'Under 25 Years Old'],
            'Casper Ruud': ['Norwegian Player', 'Clay Court Specialist', 'Right-Handed Player', 'French Open Champion'],
            'Felix Auger-Aliassime': ['Canadian Player', 'Right-Handed Player', 'Hard Court Specialist', 'Under 25 Years Old'],
            'Jannik Sinner': ['Italian Player', 'Right-Handed Player', 'Hard Court Specialist', 'Under 25 Years Old'],
            'Hubert Hurkacz': ['Polish Player', 'Right-Handed Player', 'Grass Court Specialist'],
            'Cameron Norrie': ['British Player', 'Left-Handed Player', 'Hard Court Specialist'],
            'Matteo Berrettini': ['Italian Player', 'Right-Handed Player', 'Grass Court Specialist'],
            'Taylor Fritz': ['American Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Denis Shapovalov': ['Canadian Player', 'Left-Handed Player', 'Hard Court Specialist', 'One-Handed Backhand'],
            'Gael Monfils': ['French Player', 'Right-Handed Player', 'Hard Court Specialist', 'Over 30 Years Old'],
            'Roberto Bautista Agut': ['Spanish Player', 'Right-Handed Player', 'Hard Court Specialist', 'Over 30 Years Old'],
            'Karen Khachanov': ['Russian Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Pablo Carreno Busta': ['Spanish Player', 'Right-Handed Player', 'Clay Court Specialist', 'Over 30 Years Old'],
            'Iga Swiatek': ['Polish Player', 'Multiple Grand Slams', 'Former World No. 1', 'French Open Champion', 'Clay Court Specialist', 'Right-Handed Player', 'Under 25 Years Old'],
            'Aryna Sabalenka': ['Belarusian Player', 'Grand Slam Winner', 'Australian Open Champion', 'Right-Handed Player', 'Hard Court Specialist'],
            'Jessica Pegula': ['American Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Elena Rybakina': ['Kazakhstani Player', 'Grand Slam Winner', 'Wimbledon Champion', 'Left-Handed Player', 'Grass Court Specialist'],
            'Caroline Garcia': ['French Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Ons Jabeur': ['Tunisian Player', 'Right-Handed Player', 'Grass Court Specialist'],
            'Coco Gauff': ['American Player', 'Grand Slam Winner', 'US Open Champion', 'Right-Handed Player', 'Under 25 Years Old'],
            'Maria Sakkari': ['Greek Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Petra Kvitova': ['Czech Player', 'Multiple Grand Slams', 'Wimbledon Champion', 'Left-Handed Player', 'Grass Court Specialist', 'Over 30 Years Old'],
            'Serena Williams': ['American Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'US Open Champion', 'Right-Handed Player', 'Retired Player', 'Over 30 Years Old'],
            'Venus Williams': ['American Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'US Open Champion', 'Right-Handed Player', 'Over 30 Years Old'],
            'Simona Halep': ['Romanian Player', 'Multiple Grand Slams', 'Former World No. 1', 'French Open Champion', 'Wimbledon Champion', 'Right-Handed Player', 'Over 30 Years Old'],
            'Naomi Osaka': ['Japanese Player', 'Multiple Grand Slams', 'Former World No. 1', 'US Open Champion', 'Australian Open Champion', 'Right-Handed Player', 'Hard Court Specialist'],
            'Ashleigh Barty': ['Australian Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'French Open Champion', 'Right-Handed Player', 'Retired Player'],
            'Angelique Kerber': ['German Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'US Open Champion', 'Left-Handed Player', 'Over 30 Years Old'],
            'Garbiñe Muguruza': ['Spanish Player', 'Multiple Grand Slams', 'Former World No. 1', 'French Open Champion', 'Wimbledon Champion', 'Right-Handed Player', 'Over 30 Years Old'],
            'Andy Murray': ['British Player', 'Multiple Grand Slams', 'Former World No. 1', 'Wimbledon Champion', 'US Open Champion', 'Right-Handed Player', 'Olympic Gold Medalist', 'Over 30 Years Old'],
            'Stan Wawrinka': ['Swiss Player', 'Multiple Grand Slams', 'French Open Champion', 'US Open Champion', 'Australian Open Champion', 'Right-Handed Player', 'One-Handed Backhand', 'Over 30 Years Old'],
            'Marin Cilic': ['Croatian Player', 'Grand Slam Winner', 'US Open Champion', 'Right-Handed Player', 'Hard Court Specialist', 'Over 30 Years Old'],
            'Juan Martin del Potro': ['Argentine Player', 'Grand Slam Winner', 'US Open Champion', 'Right-Handed Player', 'Hard Court Specialist', 'Over 30 Years Old'],
            'Grigor Dimitrov': ['Bulgarian Player', 'Right-Handed Player', 'Hard Court Specialist', 'One-Handed Backhand'],
            'Nick Kyrgios': ['Australian Player', 'Right-Handed Player', 'Hard Court Specialist', 'Grass Court Specialist'],
            'Alex de Minaur': ['Australian Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'John Isner': ['American Player', 'Right-Handed Player', 'Hard Court Specialist', 'Grass Court Specialist', 'Over 30 Years Old', 'Retired Player'],
            'Milos Raonic': ['Canadian Player', 'Right-Handed Player', 'Hard Court Specialist', 'Grass Court Specialist', 'Over 30 Years Old'],
            'Kei Nishikori': ['Japanese Player', 'Right-Handed Player', 'Hard Court Specialist', 'Over 30 Years Old'],
            'Dominic Thiem': ['Austrian Player', 'Grand Slam Winner', 'French Open Champion', 'US Open Champion', 'Right-Handed Player', 'Clay Court Specialist', 'One-Handed Backhand'],
            'Diego Schwartzman': ['Argentine Player', 'Right-Handed Player', 'Clay Court Specialist'],
            'Borna Coric': ['Croatian Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Sebastian Korda': ['American Player', 'Right-Handed Player', 'Hard Court Specialist', 'Under 25 Years Old'],
            'Barbora Krejcikova': ['Czech Player', 'Multiple Grand Slams', 'French Open Champion', 'Wimbledon Champion', 'Right-Handed Player', 'Clay Court Specialist'],
            'Elise Mertens': ['Belgian Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Anett Kontaveit': ['Estonian Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Danielle Collins': ['American Player', 'Right-Handed Player', 'Hard Court Specialist'],
            'Emma Raducanu': ['British Player', 'Grand Slam Winner', 'US Open Champion', 'Right-Handed Player', 'Under 25 Years Old'],
            'Leylah Fernandez': ['Canadian Player', 'Left-Handed Player', 'Hard Court Specialist', 'Under 25 Years Old'],
            'Bianca Andreescu': ['Canadian Player', 'Grand Slam Winner', 'US Open Champion', 'Right-Handed Player', 'Hard Court Specialist']
        },

        f1: {
            'Lewis Hamilton': ['British Driver', 'Multiple Championships', 'Mercedes Driver', 'Race Winner', 'Monaco GP Winner', 'British GP Winner', 'Current Driver'],
            'Max Verstappen': ['Dutch Driver', 'Multiple Championships', 'Red Bull Driver', 'Race Winner', 'Monaco GP Winner', 'Current Driver'],
            'Charles Leclerc': ['Monégasque Driver', 'Ferrari Driver', 'Race Winner', 'Monaco GP Winner', 'Current Driver', 'Pole Position'],
            'George Russell': ['British Driver', 'Mercedes Driver', 'Race Winner', 'Current Driver', 'Pole Position'],
            'Carlos Sainz Jr.': ['Spanish Driver', 'Ferrari Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Lando Norris': ['British Driver', 'McLaren Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Fernando Alonso': ['Spanish Driver', 'Multiple Championships', 'Aston Martin Driver', 'Race Winner', 'Current Driver', 'Monaco GP Winner'],
            'Esteban Ocon': ['French Driver', 'Alpine Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Pierre Gasly': ['French Driver', 'Alpine Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Sebastian Vettel': ['German Driver', 'Multiple Championships', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'German GP Winner'],
            'Valtteri Bottas': ['Finnish Driver', 'Alfa Romeo Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Zhou Guanyu': ['Chinese Driver', 'Alfa Romeo Driver', 'Current Driver', 'Rookie of the Year'],
            'Kevin Magnussen': ['Danish Driver', 'Haas Driver', 'Current Driver', 'Podium Finisher'],
            'Mick Schumacher': ['German Driver', 'Haas Driver', 'Current Driver', 'Rookie of the Year'],
            'Daniel Ricciardo': ['Australian Driver', 'McLaren Driver', 'Race Winner', 'Current Driver', 'Monaco GP Winner'],
            'Yuki Tsunoda': ['Japanese Driver', 'AlphaTauri Driver', 'Current Driver', 'Rookie of the Year'],
            'Alex Albon': ['Thai Driver', 'Williams Driver', 'Current Driver', 'Podium Finisher'],
            'Nicholas Latifi': ['Canadian Driver', 'Williams Driver', 'Current Driver', 'Rookie of the Year'],
            'Lance Stroll': ['Canadian Driver', 'Aston Martin Driver', 'Current Driver', 'Podium Finisher'],
            'Sergio Perez': ['Mexican Driver', 'Red Bull Driver', 'Race Winner', 'Current Driver', 'Monaco GP Winner'],
            'Michael Schumacher': ['German Driver', 'Multiple Championships', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'German GP Winner'],
            'Ayrton Senna': ['Brazilian Driver', 'Multiple Championships', 'McLaren Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Alain Prost': ['French Driver', 'Multiple Championships', 'McLaren Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Niki Lauda': ['Austrian Driver', 'Multiple Championships', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Jackie Stewart': ['British Driver', 'Multiple Championships', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Jim Clark': ['British Driver', 'Multiple Championships', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Juan Manuel Fangio': ['Argentine Driver', 'Multiple Championships', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Nelson Piquet': ['Brazilian Driver', 'Multiple Championships', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Nigel Mansell': ['British Driver', 'World Champion', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Damon Hill': ['British Driver', 'World Champion', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Jacques Villeneuve': ['Canadian Driver', 'World Champion', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Mika Hakkinen': ['Finnish Driver', 'Multiple Championships', 'McLaren Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'David Coulthard': ['British Driver', 'McLaren Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Rubens Barrichello': ['Brazilian Driver', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Felipe Massa': ['Brazilian Driver', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Jenson Button': ['British Driver', 'World Champion', 'McLaren Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'British GP Winner'],
            'Kimi Raikkonen': ['Finnish Driver', 'World Champion', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Mark Webber': ['Australian Driver', 'Red Bull Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Robert Kubica': ['Polish Driver', 'BMW Sauber Driver', 'Race Winner', 'Current Driver', 'Podium Finisher'],
            'Nico Rosberg': ['German Driver', 'World Champion', 'Mercedes Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner', 'German GP Winner'],
            'Pastor Maldonado': ['Venezuelan Driver', 'Williams Driver', 'Race Winner', 'Retired Driver', 'Podium Finisher'],
            'Romain Grosjean': ['French Driver', 'Haas Driver', 'Retired Driver', 'Podium Finisher'],
            'Nico Hulkenberg': ['German Driver', 'Haas Driver', 'Current Driver', 'Podium Finisher'],
            'Carlos Sainz Sr.': ['Spanish Driver', 'Retired Driver', 'Podium Finisher'],
            'Jean Alesi': ['French Driver', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Gerhard Berger': ['Austrian Driver', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Eddie Irvine': ['British Driver', 'Ferrari Driver', 'Race Winner', 'Retired Driver', 'Monaco GP Winner'],
            'Johnny Herbert': ['British Driver', 'Benetton Driver', 'Race Winner', 'Retired Driver', 'British GP Winner'],
            'Heinz-Harald Frentzen': ['German Driver', 'Jordan Driver', 'Race Winner', 'Retired Driver', 'German GP Winner'],
            'Jarno Trulli': ['Italian Driver', 'Toyota Driver', 'Retired Driver', 'Pole Position'],
            'Giancarlo Fisichella': ['Italian Driver', 'Renault Driver', 'Race Winner', 'Retired Driver', 'Podium Finisher'],
            'Oscar Piastri': ['Australian Driver', 'McLaren Driver', 'Current Driver', 'Rookie of the Year'],
            'Logan Sargeant': ['American Driver', 'Williams Driver', 'Current Driver', 'Rookie of the Year'],
            'Nyck de Vries': ['Dutch Driver', 'AlphaTauri Driver', 'Current Driver', 'Rookie of the Year'],
            'Ralf Schumacher': ['German Driver', 'Williams Driver', 'Race Winner', 'Retired Driver', 'German GP Winner'],
            'Takuma Sato': ['Japanese Driver', 'BAR Driver', 'Retired Driver', 'Podium Finisher'],
            'Kamui Kobayashi': ['Japanese Driver', 'Sauber Driver', 'Current Driver', 'Podium Finisher'],
            'Vitaly Petrov': ['Russian Driver', 'Renault Driver', 'Retired Driver', 'Podium Finisher'],
            'Jean-Eric Vergne': ['French Driver', 'Toro Rosso Driver', 'Current Driver', 'Podium Finisher'],
            'Stoffel Vandoorne': ['Belgian Driver', 'McLaren Driver', 'Current Driver', 'Podium Finisher']
        },

        tv: {
            'Richard Castle': ['From Castle', 'Male Character', 'Writer', 'Consultant', 'Uses Humor to Cope', 'Has Daddy Issues', 'Comic Relief'],
            'Kate Beckett': ['From Castle', 'Female Character', 'Detective', 'Team Leader', 'Has Trust Issues', 'Law Enforcement'],
            'Alexis Castle': ['From Castle', 'Female Character', 'Family Person', 'Young Character', 'Has Daddy Issues'],
            'Martha Rodgers': ['From Castle', 'Female Character', 'Family Person', 'Veteran Character', 'Uses Humor to Cope', 'Comic Relief'],
            'Javier Esposito': ['From Castle', 'Male Character', 'Detective', 'Law Enforcement', 'Team Member', 'Veteran Character'],
            'Kevin Ryan': ['From Castle', 'Male Character', 'Detective', 'Law Enforcement', 'Team Member', 'Family Person'],
            'Lanie Parish': ['From Castle', 'Female Character', 'Medical Examiner', 'Expert', 'Uses Humor to Cope'],
            'Patrick Jane': ['From The Mentalist', 'Male Character', 'Consultant', 'Genius Level IQ', 'Has Trust Issues', 'Reformed Criminal', 'Uses Humor to Cope'],
            'Teresa Lisbon': ['From The Mentalist', 'Female Character', 'FBI Agent', 'Team Leader', 'Law Enforcement', 'Has Trust Issues'],
            'Kimball Cho': ['From The Mentalist', 'Male Character', 'FBI Agent', 'Law Enforcement', 'Serious Character', 'Team Member'],
            'Wayne Rigsby': ['From The Mentalist', 'Male Character', 'FBI Agent', 'Law Enforcement', 'Team Member', 'Family Person'],
            'Grace Van Pelt': ['From The Mentalist', 'Female Character', 'FBI Agent', 'Law Enforcement', 'Team Member', 'Tech Specialist'],
            'Red John': ['From The Mentalist', 'Male Character', 'Antagonist', 'Criminal', 'Serial Killer', 'Genius Level IQ'],
            'Raymond Reddington': ['From Blacklist', 'Male Character', 'Criminal', 'Morally Gray Character', 'Genius Level IQ', 'Wears Suits', 'Has a Secret Identity'],
            'Elizabeth Keen': ['From Blacklist', 'Female Character', 'FBI Agent', 'Law Enforcement', 'Has Trust Issues', 'Has Daddy Issues'],
            'Donald Ressler': ['From Blacklist', 'Male Character', 'FBI Agent', 'Law Enforcement', 'Team Leader', 'By-the-book'],
            'Harold Cooper': ['From Blacklist', 'Male Character', 'FBI Agent', 'Team Leader', 'Law Enforcement', 'Mentor Figure'],
            'Aram Mojtabai': ['From Blacklist', 'Male Character', 'FBI Agent', 'Tech Specialist', 'Team Member', 'Uses Humor to Cope'],
            'Samar Navabi': ['From Blacklist', 'Female Character', 'FBI Agent', 'Law Enforcement', 'Team Member', 'International Background'],
            'Dembe Zuma': ['From Blacklist', 'Male Character', 'Bodyguard', 'Loyal Friend', 'Morally Gray Character', 'International Background'],
            'Tom Keen': ['From Blacklist', 'Male Character', 'Criminal', 'Has a Secret Identity', 'Love Interest', 'Morally Gray Character'],
            'Daniel Hondo Harrelson': ['From SWAT', 'Male Character', 'Team Leader', 'Law Enforcement', 'SWAT Officer', 'Mentor Figure'],
            'David Deacon Kay': ['From SWAT', 'Male Character', 'SWAT Officer', 'Law Enforcement', 'Team Member', 'Family Person'],
            'Victor Tan': ['From SWAT', 'Male Character', 'SWAT Officer', 'Law Enforcement', 'Team Member', 'Tech Specialist'],
            'Dominique Luca': ['From SWAT', 'Male Character', 'SWAT Officer', 'Law Enforcement', 'Team Member', 'Uses Humor to Cope'],
            'Jim Street': ['From SWAT', 'Male Character', 'SWAT Officer', 'Law Enforcement', 'Team Member', 'Rookie Character'],
            'Christina Alonso': ['From SWAT', 'Female Character', 'SWAT Officer', 'Law Enforcement', 'Team Member', 'Strong Character'],
            'Neal Caffrey': ['From White Collar', 'Male Character', 'Criminal', 'Reformed Criminal', 'Con Artist', 'Genius Level IQ', 'Wears Suits'],
            'Peter Burke': ['From White Collar', 'Male Character', 'FBI Agent', 'Law Enforcement', 'Team Leader', 'Family Person'],
            'Elizabeth Burke': ['From White Collar', 'Female Character', 'Civilian', 'Family Person', 'Love Interest', 'Strong Character'],
            'Mozzie': ['From White Collar', 'Male Character', 'Criminal', 'Tech Specialist', 'Genius Level IQ', 'Uses Humor to Cope', 'Comic Relief'],
            'Diana Berrigan': ['From White Collar', 'Female Character', 'FBI Agent', 'Law Enforcement', 'Team Member', 'Strong Character'],
            'Clinton Jones': ['From White Collar', 'Male Character', 'FBI Agent', 'Law Enforcement', 'Team Member', 'By-the-book'],
            'Sara Ellis': ['From White Collar', 'Female Character', 'Insurance Investigator', 'Love Interest', 'Expert', 'Strong Character'],
            'Malcolm Bright': ['From Prodigal Son', 'Male Character', 'Consultant', 'Genius Level IQ', 'Has Daddy Issues', 'Has Trust Issues'],
            'Gil Arroyo': ['From Prodigal Son', 'Male Character', 'Detective', 'Law Enforcement', 'Team Leader', 'Mentor Figure'],
            'Dani Powell': ['From Prodigal Son', 'Female Character', 'Detective', 'Law Enforcement', 'Team Member', 'Strong Character'],
            'JT Tarmel': ['From Prodigal Son', 'Male Character', 'Detective', 'Law Enforcement', 'Team Member', 'Family Person'],
            'Jessica Whitly': ['From Prodigal Son', 'Female Character', 'Civilian', 'Family Person', 'Has Trust Issues', 'Strong Character'],
            'Martin Whitly': ['From Prodigal Son', 'Male Character', 'Antagonist', 'Criminal', 'Serial Killer', 'Genius Level IQ', 'Manipulative'],
            'Ainsley Whitly': ['From Prodigal Son', 'Female Character', 'Journalist', 'Family Person', 'Has Daddy Issues', 'Morally Gray Character'],
            'Srikant Tiwari': ['From The Family Man', 'Male Character', 'Intelligence Agent', 'Government Agent', 'Family Person', 'Undercover Operative'],
            'JK Talpade': ['From The Family Man', 'Male Character', 'Intelligence Agent', 'Government Agent', 'Team Member', 'Tech Specialist'],
            'Saloni Tiwari': ['From The Family Man', 'Female Character', 'Civilian', 'Family Person', 'Strong Character', 'Has Trust Issues'],
            'Milind Shukla': ['From The Family Man', 'Male Character', 'Intelligence Agent', 'Government Agent', 'Team Leader', 'Veteran Character'],
            'Chellam Sir': ['From The Family Man', 'Male Character', 'Intelligence Agent', 'Consultant', 'Genius Level IQ', 'Mentor Figure'],
            'Owen Hendricks': ['From The Recruit', 'Male Character', 'CIA Agent', 'Government Agent', 'Rookie Character', 'Lawyer'],
            'Hannah Copeland': ['From The Recruit', 'Female Character', 'CIA Agent', 'Government Agent', 'Team Member', 'Mentor Figure'],
            'Max Meladze': ['From The Recruit', 'Female Character', 'Criminal', 'International Spy', 'Has a Secret Identity', 'Morally Gray Character'],
            'Violet Ebner': ['From The Recruit', 'Female Character', 'CIA Agent', 'Government Agent', 'Team Leader', 'Strong Character'],
            'Dawn Lin': ['From The Recruit', 'Female Character', 'CIA Agent', 'Government Agent', 'Team Member', 'Tech Specialist'],
            'Lester Kitchens': ['From The Recruit', 'Male Character', 'CIA Agent', 'Government Agent', 'Veteran Character', 'Mentor Figure'],
            'Nyland': ['From The Recruit', 'Male Character', 'CIA Agent', 'Government Agent', 'Team Leader', 'By-the-book']
        }
    },

    gameCategories: {
        cricket: [
            'IPL Champion', 'World Cup Winner', 'Test Captain', 'T20 Specialist', 'All-Rounder',
            'Wicket-Keeper', 'Fast Bowler', 'Spinner', 'Left-Handed Batsman', 'Right-Handed Batsman',
            'Indian Player', 'Australian Player', 'English Player', 'Pakistani Player', 'South African Player',
            'West Indies Player', 'New Zealand Player', 'Sri Lankan Player', 'Bangladeshi Player', 'Afghan Player',
            'Mumbai Indians', 'Chennai Super Kings', 'Royal Challengers Bangalore', 'Kolkata Knight Riders', 'Delhi Capitals',
            'Punjab Kings', 'Rajasthan Royals', 'Sunrisers Hyderabad', 'Test Match Specialist', 'ODI Specialist',
            'Bowled 150+ kmph', 'Scored 10000+ Runs', 'Taken 300+ Wickets', 'Played 100+ Tests', 'Retired Player'
        ],
        tennis: [
            'Grand Slam Winner', 'Wimbledon Champion', 'French Open Champion', 'US Open Champion', 'Australian Open Champion',
            'Left-Handed Player', 'Right-Handed Player', 'Serve and Volley', 'Clay Court Specialist', 'Grass Court Specialist',
            'Hard Court Specialist', 'Multiple Grand Slams', 'Former World No. 1', 'Olympic Gold Medalist', 'Davis Cup Winner',
            'Fed Cup Winner', 'American Player', 'Spanish Player', 'French Player', 'German Player',
            'Swiss Player', 'Serbian Player', 'Russian Player', 'British Player', 'Australian Player',
            'Italian Player', 'Polish Player', 'Canadian Player', 'Japanese Player', 'Argentine Player',
            'Retired Player', 'Under 25 Years Old', 'Over 30 Years Old', 'One-Handed Backhand', 'Two-Handed Backhand'
        ],
        f1: [
            'World Champion', 'Multiple Championships', 'Race Winner', 'Podium Finisher', 'Pole Position',
            'Fastest Lap', 'Mercedes Driver', 'Red Bull Driver', 'Ferrari Driver', 'McLaren Driver',
            'Alpine Driver', 'Aston Martin Driver', 'AlphaTauri Driver', 'Alfa Romeo Driver', 'Haas Driver',
            'Williams Driver', 'British Driver', 'German Driver', 'Spanish Driver', 'French Driver',
            'Dutch Driver', 'Finnish Driver', 'Brazilian Driver', 'Australian Driver', 'Mexican Driver',
            'Monaco GP Winner', 'Italian GP Winner', 'British GP Winner', 'German GP Winner', 'Belgian GP Winner',
            'Rookie of the Year', 'Retired Driver', 'Current Driver', 'Won at Monza', 'Won at Silverstone'
        ],
        tv: [
            'From Castle', 'From The Mentalist', 'From Blacklist', 'From SWAT', 'From White Collar',
            'From Prodigal Son', 'From The Family Man', 'From The Recruit', 'FBI Agent', 'Detective',
            'Criminal', 'Consultant', 'Team Leader', 'Love Interest', 'Antagonist', 'Comic Relief',
            'Has Trust Issues', 'Genius Level IQ', 'Uses Humor to Cope', 'Morally Gray Character',
            'Law Enforcement', 'Has Daddy Issues', 'Wears Suits', 'Has a Secret Identity', 'Mentor Figure',
            'Rookie Character', 'Veteran Character', 'Tech Specialist', 'Medical Examiner', 'Government Agent',
            'International Spy', 'Undercover Operative', 'Family Person', 'Loner Type', 'Reformed Criminal'
        ]
    }
};